"""Schema and process-local plumbing for the parity backend tap (PAR-01/PAR-02).

Task 1 added the record schema, `tap_env`, and `load_tap_records`. Task 2
adds the real env-gated in-scheduler instrumentation: `install` inserts a
meta_path finder (or patches immediately if the scheduler module is already
imported) so that, with RSGLANG_PARITY_TAP_DIR set, a fresh interpreter that
imports `minisgl.scheduler.scheduler` gets four methods wrapped --
Scheduler._process_one_msg, Scheduler._free_req_resources,
Scheduler._prepare_batch and SchedulerIOMixin._reply_tokenizer_rank0. Every
wrapper records, then always delegates: it returns the original's value and
lets the original's exception propagate unchanged, and its own recording
code is guarded so a recording failure never reaches the scheduler
(T-06-01). Nothing here imports minisgl directly -- install() only consults
sys.modules/sys.meta_path, so this module stays importable without the
vendored backend's CUDA-only dependencies.

Standard library only, aside from rsglang.profiling.hook.chain_load
(imported, not copied).
"""

from __future__ import annotations

import functools
import importlib.abc
import json
import os
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping

TAP_DIR_ENV = "RSGLANG_PARITY_TAP_DIR"

KIND_PATCHED = "patched"
KIND_USER = "user"
KIND_ABORT = "abort"
KIND_FREE = "free"
KIND_COLLISION = "collision"
KIND_DETOK = "detok"

_KNOWN_KINDS = {KIND_PATCHED, KIND_USER, KIND_ABORT, KIND_FREE, KIND_COLLISION, KIND_DETOK}

# The directory containing the rsglang package (python/), computed from this
# module's own path (python/rsglang/parity/tap.py -> parents[2] == python/),
# the same way rsglang.profiling.hook._RSGLANG_PARENT_DIR does.
_RSGLANG_PARENT_DIR = Path(__file__).resolve().parents[2]


@dataclass
class TapRecords:
    records: "list[dict[str, Any]]" = field(default_factory=list)
    malformed_lines: int = 0


def tap_env(base_env: Mapping[str, str], *, work_dir: Path, tap_dir: Path) -> "dict[str, str]":
    """base_env plus TAP_DIR_ENV pointed at tap_dir (created here), plus the
    generated sitecustomize shim's dir, then rsglang's parent dir, then any
    existing PYTHONPATH -- so a subprocess with this env installs the tap on
    startup.
    """
    env = dict(base_env)
    tap_dir = Path(tap_dir)
    tap_dir.mkdir(parents=True, exist_ok=True)
    env[TAP_DIR_ENV] = str(tap_dir)

    shim_dir = Path(work_dir) / "tap-shim"
    write_shim(shim_dir)
    parts = [str(shim_dir), str(_RSGLANG_PARENT_DIR)]
    existing = base_env.get("PYTHONPATH")
    if existing:
        parts.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(parts)
    return env


def load_tap_records(tap_dir: Path) -> TapRecords:
    """Read every tap-*.jsonl file in tap_dir, in sorted (filename) order.

    A line counts as malformed, and is never raised, if it is not JSON, is
    not an object, lacks kind/pid/seq, or carries an unrecognized kind.
    Well-formed records are sorted by (pid, seq).
    """
    tap_dir = Path(tap_dir)
    result = TapRecords(records=[], malformed_lines=0)
    if not tap_dir.is_dir():
        return result

    for path in sorted(tap_dir.glob("tap-*.jsonl")):
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    result.malformed_lines += 1
                    continue
                if not isinstance(record, dict):
                    result.malformed_lines += 1
                    continue
                if "kind" not in record or "pid" not in record or "seq" not in record:
                    result.malformed_lines += 1
                    continue
                if record["kind"] not in _KNOWN_KINDS:
                    result.malformed_lines += 1
                    continue
                result.records.append(record)

    result.records.sort(key=lambda r: (r["pid"], r["seq"]))
    return result


# --- generated sitecustomize shim ---------------------------------------------------

# A module-level string constant: write_shim() writes this verbatim. It
# imports rsglang.parity.tap.install only when TAP_DIR_ENV is set, then
# chain-loads any sitecustomize it shadows -- both inside try/except blocks
# that never raise into the host process, mirroring
# rsglang.profiling.hook._SHIM_SOURCE.
_SHIM_SOURCE = '''"""Generated by rsglang.parity.tap.write_shim.

Calls rsglang.parity.tap.install() only when RSGLANG_PARITY_TAP_DIR is set in
the environment, then chain-loads any sitecustomize this shim shadows.
"""
import os
import sys

if os.environ.get("RSGLANG_PARITY_TAP_DIR"):
    try:
        from rsglang.parity.tap import install

        install()
    except Exception as exc:  # the tap must never break the host process
        print(f"rsglang parity tap install failed: {exc}", file=sys.stderr)

try:
    from rsglang.profiling.hook import chain_load

    chain_load(__file__)
except Exception as exc:  # never raise into the host process
    print(f"rsglang parity tap chain-load failed: {exc}", file=sys.stderr)
'''


def write_shim(shim_dir: Path) -> Path:
    """Write the generated sitecustomize.py into shim_dir and return its path."""
    shim_dir = Path(shim_dir)
    shim_dir.mkdir(parents=True, exist_ok=True)
    path = shim_dir / "sitecustomize.py"
    path.write_text(_SHIM_SOURCE, encoding="utf-8")
    return path


# --- process-local record writer ----------------------------------------------------
#
# One append-mode handle per process, opened lazily on the first record (so a
# process that never patches anything writes nothing), guarded by a lock. seq
# increments under the same lock. Recording failures are swallowed here, not
# at each wrapper call site, so every wrapper gets the same "never raises"
# guarantee for free.

_write_lock = threading.Lock()
_file_handle: "Any | None" = None
_file_pid: "int | None" = None
_seq = 0
_warned = False


def _warn_once(exc: Exception) -> None:
    global _warned
    if _warned:
        return
    _warned = True
    print(f"rsglang parity tap recording failed: {exc}", file=sys.stderr)


def _get_handle():
    global _file_handle, _file_pid
    tap_dir = os.environ.get(TAP_DIR_ENV)
    if not tap_dir:
        return None
    if _file_handle is None:
        Path(tap_dir).mkdir(parents=True, exist_ok=True)
        _file_pid = os.getpid()
        path = Path(tap_dir) / f"tap-{_file_pid}-{time.perf_counter_ns()}.jsonl"
        _file_handle = open(path, "a", encoding="utf-8")
    return _file_handle


def _write_record(kind: str, **fields: Any) -> None:
    """Append one tap record. Never raises -- callers still guard this with
    their own try/except, since this function itself could be monkeypatched
    or otherwise fail in a way this body cannot anticipate."""
    global _seq
    with _write_lock:
        handle = _get_handle()
        if handle is None:
            return
        record = {"kind": kind, "pid": _file_pid, "seq": _seq, "t": time.monotonic()}
        record.update(fields)
        _seq += 1
        handle.write(json.dumps(record) + "\n")
        handle.flush()


# --- wrapping ------------------------------------------------------------------------

_TAP_MARKER = "__rsglang_tap__"


def _already_wrapped(fn: Any) -> bool:
    return bool(getattr(fn, _TAP_MARKER, False))


def _wrap(cls: type, name: str, make_wrapper) -> None:
    original = getattr(cls, name)
    if _already_wrapped(original):
        return
    wrapped = make_wrapper(original)
    setattr(wrapped, _TAP_MARKER, True)
    setattr(cls, name, wrapped)


def _record_process_one_msg(self: Any, msg: Any) -> None:
    kind = type(msg).__name__
    if kind == "UserMsg":
        sp = msg.sampling_params
        _write_record(
            KIND_USER,
            uid=msg.uid,
            input_ids=msg.input_ids.tolist(),
            sampling={
                "temperature": sp.temperature,
                "top_k": sp.top_k,
                "top_p": sp.top_p,
                "ignore_eos": sp.ignore_eos,
                "max_tokens": sp.max_tokens,
            },
        )
    elif kind == "AbortBackendMsg":
        pending_req = next(
            (r for r in self.prefill_manager.pending_list if r.uid == msg.uid), None
        )
        in_pending = pending_req is not None
        chunked = bool(in_pending and pending_req.chunked_req is not None)
        in_running = any(r.uid == msg.uid for r in self.decode_manager.running_reqs)
        _write_record(
            KIND_ABORT, uid=msg.uid, in_pending=in_pending, in_running=in_running, chunked=chunked
        )
    # BatchBackendMsg needs no case: the original recurses through
    # self._process_one_msg, which is this same wrapped method.


def _wrap_process_one_msg(original):
    @functools.wraps(original)
    def wrapped(self, msg):
        try:
            _record_process_one_msg(self, msg)
        except Exception as exc:  # recording must never reach the scheduler
            _warn_once(exc)
        return original(self, msg)

    return wrapped


def _wrap_free_req_resources(original):
    @functools.wraps(original)
    def wrapped(self, req):
        result = original(self, req)
        try:
            slots = self.table_manager._free_slots
            dup_free_slots = len(slots) != len(set(slots))
            _write_record(KIND_FREE, uid=req.uid, table_idx=req.table_idx, dup_free_slots=dup_free_slots)
        except Exception as exc:
            _warn_once(exc)
        return result

    return wrapped


def _record_prepare_batch(self: Any, batch: Any) -> None:
    by_table: "dict[Any, set]" = {}
    for req in list(batch.reqs) + list(self.decode_manager.running_reqs):
        by_table.setdefault(req.table_idx, set()).add(req.uid)
    for table_idx, uids in by_table.items():
        if len(uids) >= 2:
            _write_record(KIND_COLLISION, table_idx=table_idx, uids=sorted(uids))


def _wrap_prepare_batch(original):
    @functools.wraps(original)
    def wrapped(self, batch):
        try:
            _record_prepare_batch(self, batch)
        except Exception as exc:
            _warn_once(exc)
        return original(self, batch)

    return wrapped


def _wrap_reply_tokenizer_rank0(original):
    @functools.wraps(original)
    def wrapped(self, reply):
        try:
            for msg in reply:
                _write_record(KIND_DETOK, uid=msg.uid, next_token=msg.next_token, finished=msg.finished)
        except Exception as exc:
            _warn_once(exc)
        return original(self, reply)

    return wrapped


def patch(module: Any) -> None:
    """Wrap the four tap targets at class level, idempotently, then write one
    patched record naming them. `module` is the imported
    minisgl.scheduler.scheduler module; SchedulerIOMixin is read from
    sys.modules["minisgl.scheduler.io"], which is already imported by the
    time scheduler.py finishes executing (it imports SchedulerIOMixin at
    the top of the file)."""
    scheduler_cls = module.Scheduler
    io_cls = sys.modules["minisgl.scheduler.io"].SchedulerIOMixin

    _wrap(scheduler_cls, "_process_one_msg", _wrap_process_one_msg)
    _wrap(scheduler_cls, "_free_req_resources", _wrap_free_req_resources)
    _wrap(scheduler_cls, "_prepare_batch", _wrap_prepare_batch)
    _wrap(io_cls, "_reply_tokenizer_rank0", _wrap_reply_tokenizer_rank0)

    try:
        _write_record(
            KIND_PATCHED,
            targets=[
                "Scheduler._process_one_msg",
                "Scheduler._free_req_resources",
                "Scheduler._prepare_batch",
                "SchedulerIOMixin._reply_tokenizer_rank0",
            ],
        )
    except Exception as exc:
        _warn_once(exc)


class _PatchOnImport(importlib.abc.MetaPathFinder):
    """Installed at sys.meta_path[0] by install() when
    minisgl.scheduler.scheduler has not been imported yet. Resolves the
    real spec through the remaining finders (skipping itself), then wraps
    the loader's exec_module so the original module body runs first and
    patch() runs immediately after -- before any other code can observe an
    unpatched Scheduler class."""

    _TARGET = "minisgl.scheduler.scheduler"

    def find_spec(self, fullname, path, target=None):
        if fullname != self._TARGET:
            return None

        remaining = [f for f in sys.meta_path if f is not self]
        spec = None
        for finder in remaining:
            find = getattr(finder, "find_spec", None)
            if find is None:
                continue
            spec = find(fullname, path, target)
            if spec is not None:
                break
        if spec is None or spec.loader is None:
            return spec

        original_exec_module = spec.loader.exec_module

        def exec_module(module):
            original_exec_module(module)
            patch(module)

        spec.loader.exec_module = exec_module
        return spec


_installed = False


def install() -> bool:
    """Install the tap in this interpreter.

    Returns False (a no-op) unless TAP_DIR_ENV is set and non-empty and
    install() has not already run in this process. Never imports minisgl.
    """
    global _installed
    tap_dir = os.environ.get(TAP_DIR_ENV)
    if not tap_dir:
        return False
    if _installed:
        return False
    _installed = True

    if "minisgl.scheduler.scheduler" in sys.modules:
        patch(sys.modules["minisgl.scheduler.scheduler"])
    else:
        sys.meta_path.insert(0, _PatchOnImport())
    return True


def _reset_for_tests() -> None:
    """Test-only: reset all process-local tap state between tests -- the
    writer's open handle/seq/pid, the install-once flag, the warn-once flag,
    and any _PatchOnImport finder this module inserted. Does not unwrap
    already-patched methods (wrapping is idempotent and safe to leave in
    place)."""
    global _file_handle, _file_pid, _seq, _installed, _warned
    with _write_lock:
        if _file_handle is not None:
            try:
                _file_handle.close()
            except OSError:
                pass
        _file_handle = None
        _file_pid = None
        _seq = 0
    _installed = False
    _warned = False
    sys.meta_path[:] = [f for f in sys.meta_path if not isinstance(f, _PatchOnImport)]
