"""Env-gated in-process instrumentation (BENCH-01 D-02/D-03): gc.callbacks pause
timing and tracemalloc snapshots, reached through a generated sitecustomize shim.

Standard library only: this module runs inside every profiled interpreter at
process startup (api_server, scheduler, tokenize_worker, and any spawn/exec
descendant of them). It never touches vendor/mini-sglang/ and does nothing
unless RSGLANG_PROFILE_DIR is set in the environment.
"""

from __future__ import annotations

import atexit
import collections
import gc
import importlib.machinery
import importlib.util
import json
import os
import re
import sys
import threading
import time
import tracemalloc
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping

PROFILE_DIR_ENV = "RSGLANG_PROFILE_DIR"
INTERVAL_ENV = "RSGLANG_PROFILE_INTERVAL_S"
DEFAULT_INTERVAL_S = 1.0
THREAD_NAME = "rsglang-profile-hook"
TOP_ALLOC_SITES = 10

# The directory containing the rsglang package (python/), computed from this
# module's own path (python/rsglang/profiling/hook.py -> parents[2] == python/),
# so hook_env() can put it on PYTHONPATH without importing rsglang itself.
_RSGLANG_PARENT_DIR = Path(__file__).resolve().parents[2]

# A module-level string constant: write_shim() writes this verbatim. It imports
# rsglang.profiling.hook and calls install() only when RSGLANG_PROFILE_DIR is
# set, then chain-loads any sitecustomize it shadows -- both inside try/except
# blocks that never raise into the host process. This runs whether or not the
# hook is enabled, so the profiled process keeps its normal startup behavior.
_SHIM_SOURCE = '''"""Generated by rsglang.profiling.hook.write_shim.

Calls rsglang.profiling.hook.install() only when RSGLANG_PROFILE_DIR is set in
the environment, then chain-loads any sitecustomize this shim shadows.
"""
import os
import sys

if os.environ.get("RSGLANG_PROFILE_DIR"):
    try:
        from rsglang.profiling.hook import install

        install()
    except Exception as exc:  # the hook must never break the host process
        print(f"rsglang profile hook failed: {exc}", file=sys.stderr)

try:
    from rsglang.profiling.hook import chain_load

    chain_load(__file__)
except Exception as exc:  # never raise into the host process
    print(f"rsglang profile hook chain-load failed: {exc}", file=sys.stderr)
'''

_installed = False
_gc_start_t: float | None = None
_gc_pending: collections.deque = collections.deque()


def _gc_callback(phase: str, info: dict) -> None:
    """gc.callbacks entry (D-03). gc gives no duration, so this self-timestamps."""
    global _gc_start_t
    now = time.perf_counter()
    if phase == "start":
        _gc_start_t = now
    elif phase == "stop":
        t_start = _gc_start_t
        duration = now - t_start if t_start is not None else 0.0
        _gc_pending.append(
            (
                now,
                duration,
                info.get("generation", -1),
                info.get("collected", 0),
                info.get("uncollectable", 0),
            )
        )


def _interval_from_env(value: str | None) -> float:
    """The pure parser behind INTERVAL_ENV: unset/invalid/non-positive -> DEFAULT_INTERVAL_S."""
    if value is None:
        return DEFAULT_INTERVAL_S
    try:
        parsed = float(value)
    except ValueError:
        return DEFAULT_INTERVAL_S
    if parsed <= 0:
        return DEFAULT_INTERVAL_S
    return parsed


_TAG_RE = re.compile(r"^[A-Za-z0-9_-]+$")
_served_tags: set = set()


def _append_records(path: Path, records: list) -> None:
    if not records:
        return
    with open(path, "a", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record) + "\n")


def _drain(hook_file: Path) -> None:
    records = []
    while _gc_pending:
        t_stop, duration, generation, collected, uncollectable = _gc_pending.popleft()
        records.append(
            {
                "kind": "gc",
                "pid": os.getpid(),
                "t": t_stop,
                "duration_s": duration,
                "generation": generation,
                "collected": collected,
                "uncollectable": uncollectable,
            }
        )
    _append_records(hook_file, records)


def _append_mem_record(hook_file: Path) -> None:
    current, peak = tracemalloc.get_traced_memory()
    _append_records(
        hook_file,
        [
            {
                "kind": "mem",
                "pid": os.getpid(),
                "t": time.perf_counter(),
                "traced_current": current,
                "traced_peak": peak,
            }
        ],
    )


def _serve_snapshot_requests(hook_file: Path, profile_dir: Path) -> None:
    if not profile_dir.is_dir():
        return
    for req in sorted(profile_dir.glob("snapshot-*.request")):
        tag = req.name[len("snapshot-"):-len(".request")]
        if tag in _served_tags:
            continue
        _served_tags.add(tag)
        snapshot = tracemalloc.take_snapshot()
        stats = snapshot.statistics("lineno")[:TOP_ALLOC_SITES]
        sites = [
            {
                "file": stat.traceback[0].filename,
                "line": stat.traceback[0].lineno,
                "size_bytes": stat.size,
                "count": stat.count,
            }
            for stat in stats
        ]
        _append_records(
            hook_file,
            [
                {
                    "kind": "alloc_top",
                    "pid": os.getpid(),
                    "t": time.perf_counter(),
                    "tag": tag,
                    "sites": sites,
                }
            ],
        )


def _flush_loop(hook_file: Path, interval: float, profile_dir: Path) -> None:
    while True:
        time.sleep(interval)
        try:
            _drain(hook_file)
            _append_mem_record(hook_file)
            _serve_snapshot_requests(hook_file, profile_dir)
        except Exception:
            pass  # the hook thread must never raise into the host process


def _final_flush(hook_file: Path) -> None:
    try:
        _drain(hook_file)
    except Exception:
        pass


def request_snapshot(profile_dir: Path, tag: str) -> Path:
    """Ask every instrumented process in profile_dir for a top-allocation snapshot.

    Raises ValueError (and creates no file) if tag is empty or contains anything
    other than letters, digits, underscore or hyphen -- keeping it safe to use
    directly in a file name.
    """
    if not _TAG_RE.match(tag):
        raise ValueError(f"invalid snapshot tag: {tag!r}")
    profile_dir = Path(profile_dir)
    profile_dir.mkdir(parents=True, exist_ok=True)
    path = profile_dir / f"snapshot-{tag}.request"
    path.touch()
    return path


def chain_load(shim_file: str) -> None:
    """Execute the next sitecustomize this shim shadows, if any.

    Fork-without-exec children are out of scope: the default topology uses
    spawn, and every record carries its own pid, so load_hook_records()
    attributes by the "pid" field, never by file name.
    """
    shim_dir = os.path.realpath(os.path.dirname(shim_file))
    search_path = [p for p in sys.path if os.path.realpath(p or os.getcwd()) != shim_dir]
    spec = importlib.machinery.PathFinder.find_spec("sitecustomize", search_path)
    if spec is not None and spec.loader is not None:
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)


def install() -> bool:
    """Install the hook in this interpreter.

    Returns False (no-op) if RSGLANG_PROFILE_DIR is unset/empty, or install()
    already ran in this process. Returns True when it installed the hook now.
    """
    global _installed
    profile_dir = os.environ.get(PROFILE_DIR_ENV)
    if not profile_dir:
        return False
    if _installed:
        return False

    os.makedirs(profile_dir, exist_ok=True)
    pid = os.getpid()
    hook_file = Path(profile_dir) / f"hook-{pid}-{time.perf_counter_ns()}.jsonl"

    start_record = {
        "kind": "start",
        "pid": pid,
        "ppid": os.getppid(),
        "orig_argv": list(getattr(sys, "orig_argv", sys.argv)),
        "t": time.perf_counter(),
        "wall": time.time(),
        "clock": time.get_clock_info("perf_counter").implementation,
    }
    _append_records(hook_file, [start_record])

    gc.callbacks.append(_gc_callback)

    if not tracemalloc.is_tracing():
        tracemalloc.start(1)

    interval = _interval_from_env(os.environ.get(INTERVAL_ENV))
    thread = threading.Thread(
        target=_flush_loop,
        args=(hook_file, interval, Path(profile_dir)),
        name=THREAD_NAME,
        daemon=True,
    )
    thread.start()
    atexit.register(_final_flush, hook_file)

    _installed = True
    return True


def write_shim(shim_dir: Path) -> Path:
    """Write the generated sitecustomize.py into shim_dir and return its path."""
    shim_dir = Path(shim_dir)
    shim_dir.mkdir(parents=True, exist_ok=True)
    path = shim_dir / "sitecustomize.py"
    path.write_text(_SHIM_SOURCE, encoding="utf-8")
    return path


def hook_env(
    base_env: Mapping[str, str],
    *,
    shim_dir: Path,
    profile_dir: Path,
    interval_s: float,
) -> dict[str, str]:
    """base_env plus the hook's env vars and PYTHONPATH (shim_dir, then rsglang's parent dir)."""
    env = dict(base_env)
    env[PROFILE_DIR_ENV] = str(profile_dir)
    env[INTERVAL_ENV] = repr(float(interval_s))
    parts = [str(shim_dir), str(_RSGLANG_PARENT_DIR)]
    existing = base_env.get("PYTHONPATH")
    if existing:
        parts.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(parts)
    return env


@dataclass
class HookRecords:
    by_pid: dict = field(default_factory=dict)
    malformed_lines: int = 0


def load_hook_records(profile_dir: Path) -> HookRecords:
    """Read every hook-*.jsonl file in profile_dir, in sorted order.

    Every line that fails to parse, or lacks "kind"/"pid", is counted in
    malformed_lines instead of raising.
    """
    profile_dir = Path(profile_dir)
    result = HookRecords(by_pid={}, malformed_lines=0)
    if not profile_dir.is_dir():
        return result
    for path in sorted(profile_dir.glob("hook-*.jsonl")):
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    result.malformed_lines += 1
                    continue
                if not isinstance(record, dict) or "kind" not in record or "pid" not in record:
                    result.malformed_lines += 1
                    continue
                pid = record["pid"]
                if not isinstance(pid, int):
                    result.malformed_lines += 1
                    continue
                result.by_pid.setdefault(pid, []).append(record)
    return result
