"""Env-gated in-process instrumentation (BENCH-01 D-02/D-03): gc.callbacks pause
timing and tracemalloc snapshots, reached through a generated sitecustomize shim.

Standard library only: this module runs inside every profiled interpreter at
process startup (api_server, scheduler, tokenize_worker, and any spawn/exec
descendant of them). It never touches vendor/mini-sglang/ and does nothing
unless RSGLANG_PROFILE_DIR is set in the environment.
"""

from __future__ import annotations

import atexit
import collections
import gc
import json
import os
import sys
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Mapping

PROFILE_DIR_ENV = "RSGLANG_PROFILE_DIR"
INTERVAL_ENV = "RSGLANG_PROFILE_INTERVAL_S"
DEFAULT_INTERVAL_S = 1.0
THREAD_NAME = "rsglang-profile-hook"
TOP_ALLOC_SITES = 10

# The directory containing the rsglang package (python/), computed from this
# module's own path (python/rsglang/profiling/hook.py -> parents[2] == python/),
# so hook_env() can put it on PYTHONPATH without importing rsglang itself.
_RSGLANG_PARENT_DIR = Path(__file__).resolve().parents[2]

# A module-level string constant: write_shim() writes this verbatim. It imports
# rsglang.profiling.hook and calls install() only when RSGLANG_PROFILE_DIR is
# set, inside a try/except that never raises into the host process.
_SHIM_SOURCE = '''"""Generated by rsglang.profiling.hook.write_shim.

Calls rsglang.profiling.hook.install() only when RSGLANG_PROFILE_DIR is set in
the environment.
"""
import os
import sys

if os.environ.get("RSGLANG_PROFILE_DIR"):
    try:
        from rsglang.profiling.hook import install

        install()
    except Exception as exc:  # the hook must never break the host process
        print(f"rsglang profile hook failed: {exc}", file=sys.stderr)
'''

_installed = False
_gc_start_t: float | None = None
_gc_pending: collections.deque = collections.deque()


def _gc_callback(phase: str, info: dict) -> None:
    """gc.callbacks entry (D-03). gc gives no duration, so this self-timestamps."""
    global _gc_start_t
    now = time.perf_counter()
    if phase == "start":
        _gc_start_t = now
    elif phase == "stop":
        t_start = _gc_start_t
        duration = now - t_start if t_start is not None else 0.0
        _gc_pending.append(
            (
                now,
                duration,
                info.get("generation", -1),
                info.get("collected", 0),
                info.get("uncollectable", 0),
            )
        )


def _interval_from_env(value: str | None) -> float:
    """The pure parser behind INTERVAL_ENV: unset/invalid/non-positive -> DEFAULT_INTERVAL_S."""
    if value is None:
        return DEFAULT_INTERVAL_S
    try:
        parsed = float(value)
    except ValueError:
        return DEFAULT_INTERVAL_S
    if parsed <= 0:
        return DEFAULT_INTERVAL_S
    return parsed


def _append_records(path: Path, records: list) -> None:
    if not records:
        return
    with open(path, "a", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record) + "\n")


def _drain(hook_file: Path) -> None:
    records = []
    while _gc_pending:
        t_stop, duration, generation, collected, uncollectable = _gc_pending.popleft()
        records.append(
            {
                "kind": "gc",
                "pid": os.getpid(),
                "t": t_stop,
                "duration_s": duration,
                "generation": generation,
                "collected": collected,
                "uncollectable": uncollectable,
            }
        )
    _append_records(hook_file, records)


def _flush_loop(hook_file: Path, interval: float) -> None:
    while True:
        time.sleep(interval)
        try:
            _drain(hook_file)
        except Exception:
            pass  # the hook thread must never raise into the host process


def _final_flush(hook_file: Path) -> None:
    try:
        _drain(hook_file)
    except Exception:
        pass


def install() -> bool:
    """Install the hook in this interpreter.

    Returns False (no-op) if RSGLANG_PROFILE_DIR is unset/empty, or install()
    already ran in this process. Returns True when it installed the hook now.
    """
    global _installed
    profile_dir = os.environ.get(PROFILE_DIR_ENV)
    if not profile_dir:
        return False
    if _installed:
        return False

    os.makedirs(profile_dir, exist_ok=True)
    pid = os.getpid()
    hook_file = Path(profile_dir) / f"hook-{pid}-{time.perf_counter_ns()}.jsonl"

    start_record = {
        "kind": "start",
        "pid": pid,
        "ppid": os.getppid(),
        "orig_argv": list(getattr(sys, "orig_argv", sys.argv)),
        "t": time.perf_counter(),
        "wall": time.time(),
        "clock": time.get_clock_info("perf_counter").implementation,
    }
    _append_records(hook_file, [start_record])

    gc.callbacks.append(_gc_callback)

    interval = _interval_from_env(os.environ.get(INTERVAL_ENV))
    thread = threading.Thread(
        target=_flush_loop, args=(hook_file, interval), name=THREAD_NAME, daemon=True
    )
    thread.start()
    atexit.register(_final_flush, hook_file)

    _installed = True
    return True


def write_shim(shim_dir: Path) -> Path:
    """Write the generated sitecustomize.py into shim_dir and return its path."""
    shim_dir = Path(shim_dir)
    shim_dir.mkdir(parents=True, exist_ok=True)
    path = shim_dir / "sitecustomize.py"
    path.write_text(_SHIM_SOURCE, encoding="utf-8")
    return path


def hook_env(
    base_env: Mapping[str, str],
    *,
    shim_dir: Path,
    profile_dir: Path,
    interval_s: float,
) -> dict[str, str]:
    """base_env plus the hook's env vars and PYTHONPATH (shim_dir, then rsglang's parent dir)."""
    env = dict(base_env)
    env[PROFILE_DIR_ENV] = str(profile_dir)
    env[INTERVAL_ENV] = repr(float(interval_s))
    parts = [str(shim_dir), str(_RSGLANG_PARENT_DIR)]
    existing = base_env.get("PYTHONPATH")
    if existing:
        parts.append(existing)
    env["PYTHONPATH"] = os.pathsep.join(parts)
    return env


@dataclass
class HookRecords:
    by_pid: dict = field(default_factory=dict)
    malformed_lines: int = 0


def load_hook_records(profile_dir: Path) -> HookRecords:
    """Read every hook-*.jsonl file in profile_dir, in sorted order.

    Every line that fails to parse, or lacks "kind"/"pid", is counted in
    malformed_lines instead of raising.
    """
    profile_dir = Path(profile_dir)
    result = HookRecords(by_pid={}, malformed_lines=0)
    if not profile_dir.is_dir():
        return result
    for path in sorted(profile_dir.glob("hook-*.jsonl")):
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    result.malformed_lines += 1
                    continue
                if not isinstance(record, dict) or "kind" not in record or "pid" not in record:
                    result.malformed_lines += 1
                    continue
                pid = record["pid"]
                if not isinstance(pid, int):
                    result.malformed_lines += 1
                    continue
                result.by_pid.setdefault(pid, []).append(record)
    return result
